### ISSUE TITLE
The perturbation seems to be large

### ISSUE THREAD

**Issue by fiona-lxd** [liuzrcc/PIRE#1]
Thanks for your contribution first. However, in your code, line #109-#113, the perturbation v.data was multiplied with 10 or 8, which causes the perturbation actually really large. But in your paper, it writes: 'However, this approach of blindly making perturbations large is not elegant, since large perturbations lead to artifacts that are visu- ally obvious. To tackle this issue, we propose a refinement to PIRE'. It's really confusing. Can you explain it in detail?

**Comment by liuzrcc** [comment]
Thank you for your question. I did not get the email notification of this issue, so sorry for replying you late.

In order to ensure that the effect of the perturbations that are smaller than one pixel value will not be removed after saving the adversarial example into an 8-bit digital image, we enlarge the perturbation vector either by directly multiplying it with a factor (here is 10 in line 113), or the refinement in function 'enlarge_to_pixel'. There, the smaller-than-one-pixel perturbations are pre-enlarged to 1 using 'ceil()', and then a smaller multiplying factor (here 'times'=8) is sufficient to retain the same effect as done with '10' in line 113.
